#!/bin/bash

for file in "$@"; do
    if [[ $file == *.3ds ]]; then
        # Extract the filename without extension
        filename="${file%.*}"

        # Define the output format and file
        output="${filename}.obj"

        # Convert the file using ctmconv
        ctmconv "$file" "$output" && echo "Converted $file to $output" || echo "Failed to convert $file"
    else
        echo "Skipped non-3DS file $file"
    fi
done
