#!/bin/bash

# Check if any files are provided as arguments
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <file1> [<file2> ... <fileN>]"
  exit 1
fi

# Iterate over each provided file
for file in "$@"; do
  # Run demucs on the file
  demucs "$file"
  
  # Get the filename without the path and extension
  filename=$(basename -- "$file")
  extension="${filename##*.}"
  filename="${filename%.*}"

  # Define the source and destination directories
  src_dir="./separated/htdemucs/$filename"
  dest_dir=$(dirname "$file")

  # Move the folder to the destination directory
  if [ -d "$src_dir" ]; then
    for src_file in "$src_dir"/*; do
      src_filename=$(basename -- "$src_file")
      mv "$src_file" "$src_dir/$filename-$src_filename"
    done
    mv "$src_dir" "$dest_dir"
    echo "Moved and renamed files in $src_dir to $dest_dir"
  else
    echo "Error: $src_dir does not exist"
  fi
done

# Delete the separated folder
rm -rf ./separated
echo "Deleted ./separated directory"

