#!/usr/bin/env python3
import os
import subprocess

### sudo dnf install python3-gobject libnotify xclip

# Get file paths from Nautilus environment variable
paths_str = os.environ.get("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS", "")
files = paths_str.strip().split("\n") if paths_str else []

# Copy paths to clipboard
if files:
    subprocess.run(
        ["xclip", "-selection", "clipboard"],
        input="\n".join(files).encode(),
        check=True
    )

    from gi.repository import Notify #type: ignore
    Notify.init("Path Copier")
    notification = Notify.Notification.new(
        "Copied to clipboard",
        f"{files[0]}",
        "edit-copy"  # optional icon name from icon theme
    )
    notification.show()