#!/bin/bash

# Check if at least one input video is provided by Nautilus
if [ $# -eq 0 ]; then
    echo "No video file selected."
    exit 1
fi

# Call the Python script with all provided arguments
python3 /home/nicolas/Applications/frame-interpolation-pytorch/nautilus_scripts.py fps "$@" 60
