#!/bin/bash

format="png"
dpi=600

for file in "$@"; do
    filename="${file%.*}"
    output="${filename}.${format}"
    
    # Check if the file is an SVG and convert it at 150 DPI
    if [[ "${file##*.}" == "svg" ]]; then
        if convert -density $dpi "$file" "$output"; then
            echo "Converted SVG $file to $output at ${dpi} DPI"
        else
            echo "Failed to convert SVG $file"
        fi
    else
        # Convert other files to the specified format
        if mogrify -format ${format} "$file"; then
            echo "Converted $file to $output"
        else
            echo "Failed to convert $file or not a supported format"
        fi
    fi
done

