#!/bin/bash

for file in "$@"; do
    # Extract the filename without extension and the extension
    filename="${file%.*}"
    extension="${file##*.}"

    output="${filename}.${extension}"
    mogrify "$file" -resize 2048x2048\> "$output"

done

