#!/bin/bash

for file in "$@"; do
    # Extract the filename without extension and the extension
    filename="${file%.*}"
    extension="${file##*.}"

    output="${filename}.${extension}"
    mogrify "$file" -resize 4096x4096\> "$output"

done

