#!/bin/bash

# Function to convert E57 to PLY using the Python script
convert_e57_to_ply() {
    python3 /home/nicolas/.local/share/nautilus/scripts/e57_to_ply.py "$1" "$2"
}

for file in "$@"; do
    # Extract the filename without extension and the extension
    filename="${file%.*}"
    extension="${file##*.}"


    # Check if the file extension is E57
    if [ "$extension" = "e57" ]; then
	output_format="ply"
    	output="${filename}.${output_format}"

        # Check if the conversion was successful
        if convert_e57_to_ply "$file" "$output" ; then
            echo "Converted $file to $output"
        else
            echo "Failed to convert $file"
        fi
    else
        echo "Unsupported file format: $file"
        continue
    fi
done

